version: '3.8'
services:
  mongo_db:
    image: mongo:latest
    restart: always
    env_file: .env
    container_name: mongodb
    hostname: host-mongo
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - ./mongodb:/data/db
      - ./mongoInit.sh:/docker-entrypoint-initdb.d/mongoInit.sh
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
      - 'MONGO_INITDB_DATABASE=${MONGO_DATABASE}'
